# Generated by Django 5.2 on 2025-06-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Post image', 'verbose_name_plural': 'Post images'},
        ),
    ]
