# Generated by Django 4.1.8 on 2025-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='main/static/main/default_avatar.png', upload_to='avatars/'),
        ),
    ]
