# Generated by Django 5.2 on 2025-06-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_options_alter_articles_anounce_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
